<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Guance.Rum.Windows/Guance.Rum.Windows.csproj" />
    <Compile Include="../../samples/Shared/SampleRumConfig.cs" Link="SampleRumConfig.cs" />
  </ItemGroup>
</Project>
