<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <UseWinUI>true</UseWinUI>
    <UseRidGraph>true</UseRidGraph>
    <WindowsPackageType>None</WindowsPackageType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="../Shared/SampleRumConfig.cs" Link="SampleRumConfig.cs" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260710003" />
    <ProjectReference Include="../../src/Guance.Rum.Windows/Guance.Rum.Windows.csproj" />
  </ItemGroup>
</Project>
